export default {
    SECRET_KEY_SIGNATURE: process.env.SECRET_KEY_SIGNATURE,
    SECRET_KEY_ENCRYPTION: process.env.SECRET_KEY_ENCRYPTION,
    SECRET_KEY_TOTP: process.env.SECRET_KEY_TOTP,
    INVALID_USER_IDS: process.env.INVALID_USER_IDS.split(','),
    TRIGGER_INSUFFICIENT_BALANCE_AMOUNT: Number(process.env.TRIGGER_INSUFFICIENT_BALANCE_AMOUNT),
    TRIGGER_PAYMENT_ALREADY_PAID: Number(process.env.TRIGGER_PAYMENT_ALREADY_PAID),
    CSRF_CACHE_EXPIRY_IN_SEC: Number(process.env.CSRF_CACHE_EXPIRY_IN_SEC),
    DEFAULT_PIN: Number(process.env.DEFAULT_PIN),
}
