export default Object.freeze({
	API_KEY_INVALID: "API_KEY_INVALID",
	INVALID_GENERATE_ALREADY_REGISTERED: "INVALID_GENERATE_ALREADY_REGISTERED",
	INVALID_NOT_REGISTERED: "INVALID_NOT_REGISTERED",
	OFFLINE_PAYMENT_INIT_INVALID_QR: "OFFLINE_PAYMENT_INIT_INVALID_QR",
	INVALID_PAYMENT_INSUFFICIENT_BALANCE: "INVALID_PAYMENT_INSUFFICIENT_BALANCE",
	INVALID_PAYMENT_ALREADY_PAID: "INVALID_PAYMENT_ALREADY_PAID",
	OFFLINE_PAYMENT_NOT_CONFIGURED: "OFFLINE_PAYMENT_NOT_CONFIGURED",
	INVALID_OFFLINE_PAYMENT_TOKEN: "INVALID_OFFLINE_PAYMENT_TOKEN",
	CSRF_CACHE_LIMIT_REACHED: "CSRF_CACHE_LIMIT_REACHED",
	WRONG_PIN_OFFLINE_PAYMENT: "WRONG_PIN_OFFLINE_PAYMENT",
	MAXIMUM_PIN_ATTEMPT_REACHED: "MAXIMUM_PIN_ATTEMPT_REACHED",
});
