export default Object.freeze({
	INVALID_GENERATE_ALREADY_REGISTERED: "INVALID_GENERATE_ALREADY_REGISTERED",
	INVALID_NOT_REGISTERED: "INVALID_NOT_REGISTERED",
	OFFLINE_PAYMENT_INIT_INVALID_QR: "OFFLINE_PAYMENT_INIT_INVALID_QR",
	INVALID_PAYMENT_INSUFFICIENT_BALANCE: "INVALID_PAYMENT_INSUFFICIENT_BALANCE",
	INVALID_PAYMENT_ALREADY_PAID: "INVALID_PAYMENT_ALREADY_PAID",
});
